PackageIdentifier: TheTrueHooha.Bolt
PackageVersion: 0.1.1
InstallerLocale: en-US
InstallerType: zip
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/The-True-Hooha/Bolt/releases/download/v0.1.1/bolt-fm_0.1.1_windows_amd64.zip
    # update after each release
    InstallerSha256: REPLACE_WITH_SHA256_windows_amd64
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: bolt-fm_0.1.1_windows_amd64.exe
        PortableCommandAlias: bolt-fm
ManifestType: installer
ManifestVersion: 1.6.0
